window.WORKS = [
  {
    id: "goldenrod-dreams-print",
    type: "print",
    title: "Goldenrod Dreams",
    price: 150,
    image: "assets/works/goldenrod-dreams.jpg",
    medium: "Archival giclée print",
    dimensions: "30x24 in",
    year: 2023,
    available: true,
    checkoutUrl: "https://buy.stripe.com/YOUR_LINK_HERE",
    description: "Museum-grade paper, signed on the margin.",
    shipping: "Ships in 3 to 5 business days. Tracked shipping."
  },
  {
    id: "goldenrod-dreams-original",
    type: "original",
    title: "Goldenrod Dreams",
    price: 1800,
    image: "assets/works/goldenrod-dreams.jpg",
    medium: "Oil on wood panel",
    dimensions: "30x24 in",
    year: 2023,
    available: true,
    checkoutUrl: "",
  description: "Original painting. One-of-one."
},
{
  id: "sometimes-it-smells-like-oatmeal-original",
    type: "original",
    title: "Sometimes It Smells Like Oatmeal",
    price: 1800,
    image: "assets\\works\\sometimes-it-smells-like-oatmeal.jpg",
    medium: "Oil on wood panel",
    dimensions: "30x24 in",
    year: 2023,
    available: true,
    checkoutUrl: "",
    description: "Original painting. One-of-one."
},{
  id: "sometimes-it-smells-like-oatmeal-print",
    type: "print",
    title: "Sometimes It Smells Like Oatmeal",
    price: 150,
    image: "assets\\works\\sometimes-it-smells-like-oatmeal.jpg",
    medium: "Archival giclée print",
    dimensions: "30x24 in",
    year: 2023,
    available: true,
    checkoutUrl: "https://buy.stripe.com/YOUR_LINK_HERE",
  description: "Museum-grade paper, signed on the margin.",
  shipping: "Ships in 3 to 5 business days. Tracked shipping."
},
{
  id: "go-train-reflections-print",
    type: "print",
    title: "GO Train Reflections",
    price: 150,
    image: "assets/works/go-train-reflections.jpg",
    medium: "Archival giclée print",
    dimensions: "30x24 in",
    year: 2023,
    available: true,
    checkoutUrl: "https://buy.stripe.com/YOUR_LINK_HERE",
    description: "Museum-grade paper, signed on the margin.",
    shipping: "Ships in 3 to 5 business days. Tracked shipping."
  },
  {
    id: "go-train-reflections-original",
    type: "original",
    title: "GO Train Reflections",
    price: 2200,
    image: "assets/works/go-train-reflections.jpg",
    medium: "Oil on wood panel",
    dimensions: "30x24 in",
    year: 2023,
    available: true,
    checkoutUrl: "",
    description: "Original painting. One-of-one."
  },
  {
    id: "hot-pot-print",
    type: "print",
    title: "Hot Pot",
    price: 150,
    image: "assets/works/hot-pot.jpg",
    medium: "Archival giclée print",
    dimensions: "30x24 in",
    year: 2023,
    available: true,
    checkoutUrl: "https://buy.stripe.com/YOUR_LINK_HERE",
    description: "Museum-grade paper, signed on the margin.",
    shipping: "Ships in 3 to 5 business days. Tracked shipping."
  },
  {
    id: "hot-pot-original",
    type: "original",
    title: "Hot Pot",
    price: 1600,
    image: "assets/works/hot-pot.jpg",
    medium: "Oil on wood panel",
    dimensions: "30x24 in",
    year: 2023,
    available: true,
    checkoutUrl: "",
    description: "Original painting. One-of-one."
  }
];