window.WORKS = [
  {
    id: "goldenrod-dreams-print",
    type: "print",
    title: "Goldenrod Dreams",
    price: 150,
    image: "assets/works/goldenrod-dreams.jpg",
    medium: "Archival giclée print",
    dimensions: "30x24 in",
    year: 2023,
    available: true,
    checkoutUrl: "https://buy.stripe.com/YOUR_LINK_HERE",
    description: "Museum-grade paper, signed on the margin.",
    shipping: "Ships in 3 to 5 business days. Tracked shipping."
  },
  {
    id: "goldenrod-dreams-original",
    type: "original",
    title: "Goldenrod Dreams",
    price: 1800,
    image: "assets/works/goldenrod-dreams.jpg",
    medium: "Oil on wood panel",
    dimensions: "30x24 in",
    year: 2023,
    available: true,
    checkoutUrl: "",
  description: "Original painting. One-of-one."
},
{
  id: "sometimes-it-smells-like-oatmeal-original",
    type: "original",
    title: "Sometimes It Smells Like Oatmeal",
    price: 1800,
    image: "assets\\works\\sometimes-it-smells-like-oatmeal.jpg",
    medium: "Oil on wood panel",
    dimensions: "30x24 in",
    year: 2023,
    available: true,
    checkoutUrl: "",
    description: "Original painting. One-of-one."
},{
  id: "sometimes-it-smells-like-oatmeal-print",
    type: "print",
    title: "Sometimes It Smells Like Oatmeal",
    price: 150,
    image: "assets\\works\\sometimes-it-smells-like-oatmeal.jpg",
    medium: "Archival giclée print",
    dimensions: "30x24 in",
    year: 2023,
    available: true,
    checkoutUrl: "https://buy.stripe.com/YOUR_LINK_HERE",
  description: "Museum-grade paper, signed on the margin.",
  shipping: "Ships in 3 to 5 business days. Tracked shipping."
},
{
  id: "go-train-reflections-print",
    type: "print",
    title: "GO Train Reflections",
    price: 150,
    image: "assets/works/go-train-reflections.jpg",
    medium: "Archival giclée print",
    dimensions: "30x24 in",
    year: 2023,
    available: true,
    checkoutUrl: "https://buy.stripe.com/YOUR_LINK_HERE",
    description: "Museum-grade paper, signed on the margin.",
    shipping: "Ships in 3 to 5 business days. Tracked shipping."
  },
  {
    id: "go-train-reflections-original",
    type: "original",
    title: "GO Train Reflections",
    price: 2200,
    image: "assets/works/go-train-reflections.jpg",
    medium: "Oil on wood panel",
    dimensions: "30x24 in",
    year: 2023,
    available: true,
    checkoutUrl: "",
    description: "Original painting. One-of-one."
  },
  {
    id: "hot-pot-print",
    type: "print",
    title: "Hot Pot",
    price: 150,
    image: "assets/works/hot-pot.jpg",
    medium: "Archival giclée print",
    dimensions: "30x24 in",
    year: 2023,
    available: true,
    checkoutUrl: "https://buy.stripe.com/YOUR_LINK_HERE",
    description: "Museum-grade paper, signed on the margin.",
    shipping: "Ships in 3 to 5 business days. Tracked shipping."
  },
  {
    id: "hot-pot-original",
    type: "original",
    title: "Hot Pot",
    price: 1600,
    image: "assets/works/hot-pot.jpg",
    medium: "Oil on wood panel",
    dimensions: "30x24 in",
    year: 2023,
    available: true,
    checkoutUrl: "",
    description: "Original painting. One-of-one."
},
{
  id: "still-life-lemons-and-oranges-print",
    type: "print",
    title: "Still Life: Lemons and Oranges",
    price: 150,
    image: "assets/works/still-life-lemons-and-oranges.jpg",
    medium: "Archival giclée print",
    dimensions: "30x24 in",
    year: 2023,
    available: true,
    checkoutUrl: "https://buy.stripe.com/YOUR_LINK_HERE",
    description: "Museum-grade paper, signed on the margin.",
    shipping: "Ships in 3 to 5 business days. Tracked shipping."
  },
  {
    id: "still-life-lemons-and-oranges-original",
    type: "original",
    title: "Still Life: Lemons and Oranges",
    price: 1400,
    image: "assets/works/still-life-lemons-and-oranges.jpg",
    medium: "Oil on wood panel",
    dimensions: "24x20 in",
    year: 2023,
    available: true,
    checkoutUrl: "",
    description: "Original painting. One-of-one."
  },
  {
    id: "loquats-print",
    type: "print",
    title: "Loquats",
    price: 150,
    image: "assets/works/loquats.jpg",
    medium: "Archival giclée print",
    dimensions: "30x24 in",
    year: 2024,
    available: true,
    checkoutUrl: "https://buy.stripe.com/YOUR_LINK_HERE",
    description: "Museum-grade paper, signed on the margin.",
    shipping: "Ships in 3 to 5 business days. Tracked shipping."
  },
  {
    id: "loquats-original",
    type: "original",
    title: "Loquats",
    price: 1100,
    image: "assets/works/loquats.jpg",
    medium: "Oil on wood panel",
    dimensions: "30x24 in",
    year: 2024,
    available: true,
    checkoutUrl: "",
    description: "Original painting. One-of-one."
  },
  {
    id: "under-an-apple-tree-print",
    type: "print",
    title: "Under an Apple Tree",
    price: 150,
    image: "assets/works/under-an-apple-tree.jpg",
    medium: "Archival giclée print",
    dimensions: "24x24 in",
    year: 2022,
    available: true,
    checkoutUrl: "https://buy.stripe.com/YOUR_LINK_HERE",
    description: "Museum-grade paper, signed on the margin.",
    shipping: "Ships in 3 to 5 business days. Tracked shipping."
  },
  {
    id: "under-an-apple-tree-original",
    type: "original",
    title: "Under an Apple Tree",
    price: 1600,
    image: "assets/works/under-an-apple-tree.jpg",
    medium: "Oil on wood panel",
    dimensions: "24x24 in",
    year: 2022,
    available: true,
    checkoutUrl: "",
    description: "Original painting. One-of-one."
  },
  {
    id: "plums-peaches-and-a-crossword-print",
    type: "print",
    title: "Plums, Peaches, and a Crossword",
    price: 150,
    image: "assets/works/plums-peaches-and-a-crossword.jpg",
    medium: "Archival giclée print",
    dimensions: "24x24 in",
    year: 2025,
    available: true,
    checkoutUrl: "https://buy.stripe.com/YOUR_LINK_HERE",
    description: "Museum-grade paper, signed on the margin.",
    shipping: "Ships in 3 to 5 business days. Tracked shipping."
  },
];